xbos:
    waved: localhost:777
    wavemq: localhost:4516
    base_resource: emulated_battery_test
    entity:
    namespace:
    publish_rate: 60
    check_setpoint_rate: 30
    heartbeat_rate: 60
    service_name: battery
    id: emulated-battery-driver
    fmu_file: SolarPlus_Batteries_Emulator.fmu

device_config:
    model_update_rate: 30
    initial_SOC: 0
    default_real_power_setpoint: 0
    min_real_power_setpoint: -109000
    max_real_power_setpoint: 109000
    time_threshold_revert_to_default: 14400