// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flexstat.proto

package xbospb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FlexstatState struct {
	// space temperature reading
	// unit: F
	SpaceTempSensor *Double `protobuf:"bytes,1,opt,name=space_temp_sensor,json=spaceTempSensor,proto3" json:"space_temp_sensor,omitempty"`
	// minimum P value for of the PI control
	// unit: F
	MinimumProportional *Double `protobuf:"bytes,2,opt,name=minimum_proportional,json=minimumProportional,proto3" json:"minimum_proportional,omitempty"`
	// active cooling setpoint
	// unit: F
	ActiveCoolingSetpt *Double `protobuf:"bytes,3,opt,name=active_cooling_setpt,json=activeCoolingSetpt,proto3" json:"active_cooling_setpt,omitempty"`
	// active heating setpoint
	// unit: F
	ActiveHeatingSetpt *Double `protobuf:"bytes,4,opt,name=active_heating_setpt,json=activeHeatingSetpt,proto3" json:"active_heating_setpt,omitempty"`
	// cooling setpoint during unoccupied times
	// unit: F
	UnoccCoolingSetpt *Double `protobuf:"bytes,5,opt,name=unocc_cooling_setpt,json=unoccCoolingSetpt,proto3" json:"unocc_cooling_setpt,omitempty"`
	// heating setpoint during unoccupied times
	// unit: F
	UnoccHeatingSetpt *Double `protobuf:"bytes,6,opt,name=unocc_heating_setpt,json=unoccHeatingSetpt,proto3" json:"unocc_heating_setpt,omitempty"`
	// minimum cooling setpoint during occupied times
	// unit: F
	OccMinClgSetpt *Double `protobuf:"bytes,7,opt,name=occ_min_clg_setpt,json=occMinClgSetpt,proto3" json:"occ_min_clg_setpt,omitempty"`
	// maximum heating setpoint during occupied times
	// unit: F
	OccMaxHtgSetpt *Double `protobuf:"bytes,8,opt,name=occ_max_htg_setpt,json=occMaxHtgSetpt,proto3" json:"occ_max_htg_setpt,omitempty"`
	// override timer
	// unit: hours
	OverrideTimer *Double `protobuf:"bytes,9,opt,name=override_timer,json=overrideTimer,proto3" json:"override_timer,omitempty"`
	// cooling setpoint during occupied times
	// unit: F
	OccCoolingSetpt *Double `protobuf:"bytes,10,opt,name=occ_cooling_setpt,json=occCoolingSetpt,proto3" json:"occ_cooling_setpt,omitempty"`
	// heating setpoint during occupied times
	// unit: F
	OccHeatingSetpt *Double `protobuf:"bytes,11,opt,name=occ_heating_setpt,json=occHeatingSetpt,proto3" json:"occ_heating_setpt,omitempty"`
	// setpoint for the current mode (heating or cooling)
	// unit: F
	CurrentModeSetpt *Double `protobuf:"bytes,12,opt,name=current_mode_setpt,json=currentModeSetpt,proto3" json:"current_mode_setpt,omitempty"`
	// setpoint from the user interface on the thermostat
	// unit: F
	UiSetpt *Double `protobuf:"bytes,13,opt,name=ui_setpt,json=uiSetpt,proto3" json:"ui_setpt,omitempty"`
	// cooling need
	// unit: F
	CoolingNeed *Double `protobuf:"bytes,14,opt,name=cooling_need,json=coolingNeed,proto3" json:"cooling_need,omitempty"`
	// heating need
	// unit: F
	HeatingNeed *Double `protobuf:"bytes,15,opt,name=heating_need,json=heatingNeed,proto3" json:"heating_need,omitempty"`
	// minimum cooling setpoint during unoccupied times
	// unit: F
	UnoccMinClgSetpt *Double `protobuf:"bytes,16,opt,name=unocc_min_clg_setpt,json=unoccMinClgSetpt,proto3" json:"unocc_min_clg_setpt,omitempty"`
	// maximum heating setpoint during unoccupied times
	// unit: F
	UnoccMaxHtgSetpt *Double `protobuf:"bytes,17,opt,name=unocc_max_htg_setpt,json=unoccMaxHtgSetpt,proto3" json:"unocc_max_htg_setpt,omitempty"`
	// minimum difference between heating and cooling setpoint
	// unit: F
	MinSetptDiff *Double `protobuf:"bytes,18,opt,name=min_setpt_diff,json=minSetptDiff,proto3" json:"min_setpt_diff,omitempty"`
	// minimum setpoint limit
	// unit: F
	MinSetptLimit *Double `protobuf:"bytes,19,opt,name=min_setpt_limit,json=minSetptLimit,proto3" json:"min_setpt_limit,omitempty"`
	// space temperature reading
	// unit: F
	SpaceTemp *Double `protobuf:"bytes,20,opt,name=space_temp,json=spaceTemp,proto3" json:"space_temp,omitempty"`
	// cooling P value of the PI control
	// unit: F
	CoolingProp *Double `protobuf:"bytes,21,opt,name=cooling_prop,json=coolingProp,proto3" json:"cooling_prop,omitempty"`
	// heating P value of the PI control
	// unit: F
	HeatingProp *Double `protobuf:"bytes,22,opt,name=heating_prop,json=heatingProp,proto3" json:"heating_prop,omitempty"`
	// cooling I value of the PI control
	// unit: per hour
	CoolingIntg *Double `protobuf:"bytes,23,opt,name=cooling_intg,json=coolingIntg,proto3" json:"cooling_intg,omitempty"`
	// heating I value of the PI control
	// unit: per hour
	HeatingIntg *Double `protobuf:"bytes,24,opt,name=heating_intg,json=heatingIntg,proto3" json:"heating_intg,omitempty"`
	// is fan on or off
	// unit: T/F
	Fan *Int64 `protobuf:"bytes,25,opt,name=fan,proto3" json:"fan,omitempty"`
	// is occupied or not
	// unit: T/F
	OccupancyMode *Int64 `protobuf:"bytes,26,opt,name=occupancy_mode,json=occupancyMode,proto3" json:"occupancy_mode,omitempty"`
	// is setpoint override on or off
	// unit: T/F
	SetptOverrideMode *Int64 `protobuf:"bytes,27,opt,name=setpt_override_mode,json=setptOverrideMode,proto3" json:"setpt_override_mode,omitempty"`
	// is there a fan alaram happening
	// unit: T/F
	FanAlarm *Int64 `protobuf:"bytes,28,opt,name=fan_alarm,json=fanAlarm,proto3" json:"fan_alarm,omitempty"`
	// is there a need for fan right now
	// unit: T/F
	FanNeed *Int64 `protobuf:"bytes,29,opt,name=fan_need,json=fanNeed,proto3" json:"fan_need,omitempty"`
	// is the hvac system in heating mode or not
	// unit: T/F
	HeatingCoolingMode *Int64 `protobuf:"bytes,30,opt,name=heating_cooling_mode,json=heatingCoolingMode,proto3" json:"heating_cooling_mode,omitempty"`
	// during occupied times, is fan on auto mode or on mode
	// unit: T/F
	OccFanAutoOn *Int64 `protobuf:"bytes,31,opt,name=occ_fan_auto_on,json=occFanAutoOn,proto3" json:"occ_fan_auto_on,omitempty"`
	// during unoccupied times, is fan on auto mode or on mode
	// unit: T/F
	UnoccFanAutoOn *Int64 `protobuf:"bytes,32,opt,name=unocc_fan_auto_on,json=unoccFanAutoOn,proto3" json:"unocc_fan_auto_on,omitempty"`
	// fan status
	// unit: T/F
	FanStatus *Int64 `protobuf:"bytes,33,opt,name=fan_status,json=fanStatus,proto3" json:"fan_status,omitempty"`
	// epoch time
	// unit: seconds
	Time                 uint64   `protobuf:"varint,34,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlexstatState) Reset()         { *m = FlexstatState{} }
func (m *FlexstatState) String() string { return proto.CompactTextString(m) }
func (*FlexstatState) ProtoMessage()    {}
func (*FlexstatState) Descriptor() ([]byte, []int) {
	return fileDescriptor_flexstat_03a87d373423983b, []int{0}
}
func (m *FlexstatState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlexstatState.Unmarshal(m, b)
}
func (m *FlexstatState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlexstatState.Marshal(b, m, deterministic)
}
func (dst *FlexstatState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlexstatState.Merge(dst, src)
}
func (m *FlexstatState) XXX_Size() int {
	return xxx_messageInfo_FlexstatState.Size(m)
}
func (m *FlexstatState) XXX_DiscardUnknown() {
	xxx_messageInfo_FlexstatState.DiscardUnknown(m)
}

var xxx_messageInfo_FlexstatState proto.InternalMessageInfo

func (m *FlexstatState) GetSpaceTempSensor() *Double {
	if m != nil {
		return m.SpaceTempSensor
	}
	return nil
}

func (m *FlexstatState) GetMinimumProportional() *Double {
	if m != nil {
		return m.MinimumProportional
	}
	return nil
}

func (m *FlexstatState) GetActiveCoolingSetpt() *Double {
	if m != nil {
		return m.ActiveCoolingSetpt
	}
	return nil
}

func (m *FlexstatState) GetActiveHeatingSetpt() *Double {
	if m != nil {
		return m.ActiveHeatingSetpt
	}
	return nil
}

func (m *FlexstatState) GetUnoccCoolingSetpt() *Double {
	if m != nil {
		return m.UnoccCoolingSetpt
	}
	return nil
}

func (m *FlexstatState) GetUnoccHeatingSetpt() *Double {
	if m != nil {
		return m.UnoccHeatingSetpt
	}
	return nil
}

func (m *FlexstatState) GetOccMinClgSetpt() *Double {
	if m != nil {
		return m.OccMinClgSetpt
	}
	return nil
}

func (m *FlexstatState) GetOccMaxHtgSetpt() *Double {
	if m != nil {
		return m.OccMaxHtgSetpt
	}
	return nil
}

func (m *FlexstatState) GetOverrideTimer() *Double {
	if m != nil {
		return m.OverrideTimer
	}
	return nil
}

func (m *FlexstatState) GetOccCoolingSetpt() *Double {
	if m != nil {
		return m.OccCoolingSetpt
	}
	return nil
}

func (m *FlexstatState) GetOccHeatingSetpt() *Double {
	if m != nil {
		return m.OccHeatingSetpt
	}
	return nil
}

func (m *FlexstatState) GetCurrentModeSetpt() *Double {
	if m != nil {
		return m.CurrentModeSetpt
	}
	return nil
}

func (m *FlexstatState) GetUiSetpt() *Double {
	if m != nil {
		return m.UiSetpt
	}
	return nil
}

func (m *FlexstatState) GetCoolingNeed() *Double {
	if m != nil {
		return m.CoolingNeed
	}
	return nil
}

func (m *FlexstatState) GetHeatingNeed() *Double {
	if m != nil {
		return m.HeatingNeed
	}
	return nil
}

func (m *FlexstatState) GetUnoccMinClgSetpt() *Double {
	if m != nil {
		return m.UnoccMinClgSetpt
	}
	return nil
}

func (m *FlexstatState) GetUnoccMaxHtgSetpt() *Double {
	if m != nil {
		return m.UnoccMaxHtgSetpt
	}
	return nil
}

func (m *FlexstatState) GetMinSetptDiff() *Double {
	if m != nil {
		return m.MinSetptDiff
	}
	return nil
}

func (m *FlexstatState) GetMinSetptLimit() *Double {
	if m != nil {
		return m.MinSetptLimit
	}
	return nil
}

func (m *FlexstatState) GetSpaceTemp() *Double {
	if m != nil {
		return m.SpaceTemp
	}
	return nil
}

func (m *FlexstatState) GetCoolingProp() *Double {
	if m != nil {
		return m.CoolingProp
	}
	return nil
}

func (m *FlexstatState) GetHeatingProp() *Double {
	if m != nil {
		return m.HeatingProp
	}
	return nil
}

func (m *FlexstatState) GetCoolingIntg() *Double {
	if m != nil {
		return m.CoolingIntg
	}
	return nil
}

func (m *FlexstatState) GetHeatingIntg() *Double {
	if m != nil {
		return m.HeatingIntg
	}
	return nil
}

func (m *FlexstatState) GetFan() *Int64 {
	if m != nil {
		return m.Fan
	}
	return nil
}

func (m *FlexstatState) GetOccupancyMode() *Int64 {
	if m != nil {
		return m.OccupancyMode
	}
	return nil
}

func (m *FlexstatState) GetSetptOverrideMode() *Int64 {
	if m != nil {
		return m.SetptOverrideMode
	}
	return nil
}

func (m *FlexstatState) GetFanAlarm() *Int64 {
	if m != nil {
		return m.FanAlarm
	}
	return nil
}

func (m *FlexstatState) GetFanNeed() *Int64 {
	if m != nil {
		return m.FanNeed
	}
	return nil
}

func (m *FlexstatState) GetHeatingCoolingMode() *Int64 {
	if m != nil {
		return m.HeatingCoolingMode
	}
	return nil
}

func (m *FlexstatState) GetOccFanAutoOn() *Int64 {
	if m != nil {
		return m.OccFanAutoOn
	}
	return nil
}

func (m *FlexstatState) GetUnoccFanAutoOn() *Int64 {
	if m != nil {
		return m.UnoccFanAutoOn
	}
	return nil
}

func (m *FlexstatState) GetFanStatus() *Int64 {
	if m != nil {
		return m.FanStatus
	}
	return nil
}

func (m *FlexstatState) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*FlexstatState)(nil), "xbospb.FlexstatState")
}

func init() { proto.RegisterFile("flexstat.proto", fileDescriptor_flexstat_03a87d373423983b) }

var fileDescriptor_flexstat_03a87d373423983b = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x95, 0xdb, 0x4e, 0xdc, 0x3c,
	0x10, 0x80, 0xc5, 0x0f, 0x3f, 0x87, 0x61, 0x37, 0xb0, 0xde, 0x6d, 0xeb, 0xd2, 0x03, 0x94, 0x2b,
	0x5a, 0xb5, 0x48, 0x6d, 0x29, 0x6a, 0xab, 0x9e, 0x10, 0x08, 0x81, 0x54, 0x4a, 0xc5, 0x72, 0x6f,
	0x79, 0xbd, 0x0e, 0x58, 0x4a, 0xec, 0x28, 0x71, 0xd0, 0xf2, 0x8e, 0x7d, 0xa8, 0xca, 0x93, 0x64,
	0x37, 0xa1, 0x26, 0x77, 0x91, 0xfc, 0x7d, 0xe3, 0xc9, 0xcc, 0x64, 0x02, 0x41, 0x18, 0xc9, 0x49,
	0x66, 0xb9, 0xdd, 0x4d, 0x52, 0x63, 0x0d, 0x59, 0x9c, 0x8c, 0x4c, 0x96, 0x8c, 0x36, 0xfa, 0x3a,
	0x8f, 0x22, 0x3e, 0x8a, 0xa4, 0xbd, 0x4d, 0x64, 0x56, 0x1c, 0x6e, 0xff, 0x09, 0xa0, 0x7b, 0x5c,
	0xf2, 0x43, 0xcb, 0xad, 0x24, 0x9f, 0xa1, 0x97, 0x25, 0x5c, 0x48, 0x66, 0x65, 0x9c, 0xb0, 0x4c,
	0xea, 0xcc, 0xa4, 0x74, 0x6e, 0x6b, 0x6e, 0x67, 0xf5, 0x5d, 0xb0, 0x5b, 0x84, 0xda, 0x3d, 0x32,
	0xf9, 0x28, 0x92, 0x17, 0x6b, 0x08, 0x5e, 0xca, 0x38, 0x19, 0x22, 0x46, 0x0e, 0x60, 0x10, 0x2b,
	0xad, 0xe2, 0x3c, 0x66, 0x49, 0x6a, 0x12, 0x93, 0x5a, 0x65, 0x34, 0x8f, 0xe8, 0x7f, 0x5e, 0xbd,
	0x5f, 0xb2, 0xbf, 0x6b, 0x28, 0xf9, 0x01, 0x03, 0x2e, 0xac, 0xba, 0x91, 0x4c, 0x18, 0x13, 0x29,
	0x7d, 0xc5, 0x32, 0x69, 0x13, 0x4b, 0xe7, 0xbd, 0x21, 0x48, 0xc1, 0x1e, 0x16, 0xe8, 0xd0, 0x91,
	0xb5, 0x08, 0xd7, 0x92, 0xdb, 0x59, 0x84, 0x85, 0xb6, 0x08, 0x27, 0x05, 0x5a, 0x44, 0xf8, 0x06,
	0xfd, 0x5c, 0x1b, 0x21, 0xee, 0xa4, 0xf0, 0xbf, 0x37, 0x40, 0x0f, 0xd1, 0x46, 0x06, 0x53, 0xbf,
	0x99, 0xc0, 0x62, 0x8b, 0xdf, 0xb8, 0xff, 0x13, 0xf4, 0x9c, 0x1d, 0x2b, 0xcd, 0x44, 0x54, 0xd9,
	0x4b, 0x5e, 0x3b, 0x30, 0x42, 0x9c, 0x29, 0x7d, 0x18, 0xdd, 0x51, 0xf9, 0x84, 0x5d, 0xdb, 0x4a,
	0x5d, 0xbe, 0x5f, 0xe5, 0x93, 0x13, 0x5b, 0xaa, 0x1f, 0x20, 0x30, 0x37, 0x32, 0x4d, 0xd5, 0x58,
	0x32, 0xab, 0x62, 0x99, 0xd2, 0x15, 0xaf, 0xd7, 0xad, 0xa8, 0x4b, 0x07, 0xb9, 0x79, 0xf9, 0xb7,
	0x54, 0xe0, 0x9f, 0x97, 0xbb, 0x85, 0x2a, 0xdd, 0x66, 0x99, 0x56, 0xef, 0x75, 0x1b, 0x45, 0xfa,
	0x02, 0x44, 0xe4, 0x69, 0x2a, 0xb5, 0x65, 0xb1, 0x19, 0xcb, 0x52, 0xee, 0x78, 0xe5, 0xf5, 0x92,
	0x3c, 0x33, 0x63, 0x59, 0xd8, 0x2f, 0x61, 0x39, 0x57, 0xa5, 0xd3, 0xf5, 0x3a, 0x4b, 0xb9, 0x2a,
	0xd0, 0xb7, 0xd0, 0xa9, 0x5e, 0x4e, 0x4b, 0x39, 0xa6, 0x81, 0x17, 0x5f, 0x2d, 0x99, 0x5f, 0x52,
	0x8e, 0x9d, 0x52, 0xbd, 0x13, 0x2a, 0x6b, 0x7e, 0xa5, 0x64, 0x50, 0xf9, 0x5a, 0xcd, 0x4c, 0xb3,
	0xeb, 0xeb, 0xfe, 0xf7, 0x41, 0xb4, 0xde, 0xf7, 0x99, 0xde, 0xe8, 0x7c, 0xaf, 0x4d, 0xaf, 0xf5,
	0x7e, 0x0f, 0x02, 0x77, 0x2f, 0x4a, 0x6c, 0xac, 0xc2, 0x90, 0x12, 0xaf, 0xd9, 0x89, 0x95, 0x46,
	0xe3, 0x48, 0x85, 0x21, 0xd9, 0x87, 0xb5, 0x99, 0x15, 0xa9, 0x58, 0x59, 0xda, 0xf7, 0x8f, 0x4c,
	0xa5, 0xfd, 0x74, 0x10, 0x79, 0x03, 0x30, 0x5b, 0x31, 0x74, 0xe0, 0x55, 0x56, 0xa6, 0xbb, 0xa5,
	0xde, 0x00, 0xb7, 0x55, 0xe8, 0x83, 0xd6, 0x06, 0xb8, 0x6d, 0x52, 0x6f, 0x00, 0x2a, 0x0f, 0x5b,
	0x1b, 0x50, 0x29, 0xd5, 0x2d, 0x4a, 0xdb, 0x2b, 0xfa, 0xa8, 0xf5, 0x96, 0x53, 0x6d, 0xaf, 0xea,
	0xb7, 0xa0, 0x42, 0x5b, 0x6f, 0x41, 0x65, 0x13, 0xe6, 0x43, 0xae, 0xe9, 0x63, 0x24, 0xbb, 0x15,
	0x79, 0xaa, 0xed, 0xfe, 0xde, 0x85, 0x3b, 0x71, 0x9d, 0x30, 0x42, 0xe4, 0x09, 0xd7, 0xe2, 0x16,
	0x07, 0x9b, 0x6e, 0xf8, 0xd8, 0xee, 0x14, 0x72, 0x33, 0xed, 0xda, 0x5f, 0x74, 0x61, 0xfa, 0x05,
	0xa3, 0xfa, 0xc4, 0xa7, 0xf6, 0x90, 0x3c, 0x2f, 0x41, 0xd4, 0x5f, 0xc1, 0x4a, 0xc8, 0x35, 0xe3,
	0x11, 0x4f, 0x63, 0xfa, 0xd4, 0x27, 0x2d, 0x87, 0x5c, 0x1f, 0xb8, 0x63, 0xb2, 0x03, 0xee, 0xb9,
	0x98, 0xeb, 0x67, 0x3e, 0x74, 0x29, 0xe4, 0x1a, 0x47, 0xfa, 0x3b, 0x0c, 0xaa, 0xf2, 0x54, 0x95,
	0xc5, 0xac, 0x9e, 0xfb, 0x2c, 0x52, 0xa2, 0xe5, 0x7e, 0xc0, 0xb4, 0xf6, 0xc0, 0x7d, 0xf5, 0x0c,
	0x53, 0xcb, 0xad, 0x61, 0x46, 0xd3, 0x4d, 0x9f, 0xdb, 0x31, 0x42, 0x1c, 0x73, 0x7d, 0x90, 0x5b,
	0x73, 0xae, 0xc9, 0x47, 0x28, 0x56, 0x6a, 0xc3, 0xdb, 0xf2, 0x79, 0x01, 0x72, 0x33, 0xf3, 0x35,
	0x80, 0x73, 0xdc, 0xbf, 0x30, 0xcf, 0xe8, 0x0b, 0x9f, 0xe2, 0xea, 0x34, 0xc4, 0x73, 0x42, 0x60,
	0xc1, 0xad, 0x49, 0xba, 0xbd, 0x35, 0xb7, 0xb3, 0x70, 0x81, 0xcf, 0xa3, 0x45, 0xfc, 0xab, 0xbe,
	0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xd5, 0x5e, 0x9d, 0x84, 0x07, 0x00, 0x00,
}
