dark_sky:
    api: 763827c188fa2c8c4cca914f16caf2d0
    url: https://api.darksky.net/forecast/
    coordinates: 40.5301,-124.0000 # Should be near BLR

local_database_config:
    host: localhost
    database: dark_sky
    protocol: json
    port: 8086
    use_ssl: False
    verify_ssl_is_on: False
    measurement_name: btu_meters
    username: admin
    password: password
    tags:
    sensor_id:
    tag_dict: {}
    fields: []

# Not sure if this will be used for weather
remote_database_config:
    host: localhost
    database: remote_dark_sky_test
    protocol: json
    port: 8086
    use_ssl: False
    verify_ssl_is_on: False
    measurement_name: btu_meters
    username: admin
    password: password
    tags:
    sensor_id:
    tag_dict: {}
    fields: []
