// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xbos.proto

package xbospb

/*
This defines the protocol buffers used by XBOS with WaveMQ. The schema for
a wavemq xbos proto message is:
  xbosproto/RootMessageType

Version 1.0
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transport int32

const (
	Transport_WAVEMQ Transport = 0
	Transport_GRPC   Transport = 1
)

var Transport_name = map[int32]string{
	0: "WAVEMQ",
	1: "GRPC",
}
var Transport_value = map[string]int32{
	"WAVEMQ": 0,
	"GRPC":   1,
}

func (x Transport) String() string {
	return proto.EnumName(Transport_name, int32(x))
}
func (Transport) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_xbos_dcf0799e4426b35d, []int{0}
}

// Root union type
// We reserve 50 fields per imported file
type XBOS struct {
	// Hamilton Fields
	HamiltonData        *HamiltonData        `protobuf:"bytes,50,opt,name=HamiltonData,proto3" json:"HamiltonData,omitempty"`
	HamiltonBRLinkStats *HamiltonBRLinkStats `protobuf:"bytes,51,opt,name=HamiltonBRLinkStats,proto3" json:"HamiltonBRLinkStats,omitempty"`
	HamiltonBRMessage   *HamiltonBRMessage   `protobuf:"bytes,52,opt,name=HamiltonBRMessage,proto3" json:"HamiltonBRMessage,omitempty"`
	// IoT Fields
	XBOSIoTDeviceState     *XBOSIoTDeviceState     `protobuf:"bytes,100,opt,name=XBOSIoTDeviceState,proto3" json:"XBOSIoTDeviceState,omitempty"`
	XBOSIoTDeviceActuation *XBOSIoTDeviceActuation `protobuf:"bytes,101,opt,name=XBOSIoTDeviceActuation,proto3" json:"XBOSIoTDeviceActuation,omitempty"`
	XBOSIoTContext         *XBOSIoTContext         `protobuf:"bytes,102,opt,name=XBOSIoTContext,proto3" json:"XBOSIoTContext,omitempty"`
	// Vendor-specific Device Fields
	DentMeterState *DentMeterState `protobuf:"bytes,150,opt,name=DentMeterState,proto3" json:"DentMeterState,omitempty"`
	ParkerState    *ParkerState    `protobuf:"bytes,151,opt,name=parker_state,json=parkerState,proto3" json:"parker_state,omitempty"`
	WattnodeState  *WattnodeState  `protobuf:"bytes,152,opt,name=wattnode_state,json=wattnodeState,proto3" json:"wattnode_state,omitempty"`
	FlexstatState  *FlexstatState  `protobuf:"bytes,153,opt,name=flexstat_state,json=flexstatState,proto3" json:"flexstat_state,omitempty"`
	// System Status Fields
	BasicServerStatus *BasicServerStatus `protobuf:"bytes,200,opt,name=BasicServerStatus,proto3" json:"BasicServerStatus,omitempty"`
	// External Protocols
	C37DataFrame         *C37DataFrame    `protobuf:"bytes,250,opt,name=C37DataFrame,proto3" json:"C37DataFrame,omitempty"`
	EnergiseMessage      *EnergiseMessage `protobuf:"bytes,251,opt,name=EnergiseMessage,proto3" json:"EnergiseMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *XBOS) Reset()         { *m = XBOS{} }
func (m *XBOS) String() string { return proto.CompactTextString(m) }
func (*XBOS) ProtoMessage()    {}
func (*XBOS) Descriptor() ([]byte, []int) {
	return fileDescriptor_xbos_dcf0799e4426b35d, []int{0}
}
func (m *XBOS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XBOS.Unmarshal(m, b)
}
func (m *XBOS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XBOS.Marshal(b, m, deterministic)
}
func (dst *XBOS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XBOS.Merge(dst, src)
}
func (m *XBOS) XXX_Size() int {
	return xxx_messageInfo_XBOS.Size(m)
}
func (m *XBOS) XXX_DiscardUnknown() {
	xxx_messageInfo_XBOS.DiscardUnknown(m)
}

var xxx_messageInfo_XBOS proto.InternalMessageInfo

func (m *XBOS) GetHamiltonData() *HamiltonData {
	if m != nil {
		return m.HamiltonData
	}
	return nil
}

func (m *XBOS) GetHamiltonBRLinkStats() *HamiltonBRLinkStats {
	if m != nil {
		return m.HamiltonBRLinkStats
	}
	return nil
}

func (m *XBOS) GetHamiltonBRMessage() *HamiltonBRMessage {
	if m != nil {
		return m.HamiltonBRMessage
	}
	return nil
}

func (m *XBOS) GetXBOSIoTDeviceState() *XBOSIoTDeviceState {
	if m != nil {
		return m.XBOSIoTDeviceState
	}
	return nil
}

func (m *XBOS) GetXBOSIoTDeviceActuation() *XBOSIoTDeviceActuation {
	if m != nil {
		return m.XBOSIoTDeviceActuation
	}
	return nil
}

func (m *XBOS) GetXBOSIoTContext() *XBOSIoTContext {
	if m != nil {
		return m.XBOSIoTContext
	}
	return nil
}

func (m *XBOS) GetDentMeterState() *DentMeterState {
	if m != nil {
		return m.DentMeterState
	}
	return nil
}

func (m *XBOS) GetParkerState() *ParkerState {
	if m != nil {
		return m.ParkerState
	}
	return nil
}

func (m *XBOS) GetWattnodeState() *WattnodeState {
	if m != nil {
		return m.WattnodeState
	}
	return nil
}

func (m *XBOS) GetFlexstatState() *FlexstatState {
	if m != nil {
		return m.FlexstatState
	}
	return nil
}

func (m *XBOS) GetBasicServerStatus() *BasicServerStatus {
	if m != nil {
		return m.BasicServerStatus
	}
	return nil
}

func (m *XBOS) GetC37DataFrame() *C37DataFrame {
	if m != nil {
		return m.C37DataFrame
	}
	return nil
}

func (m *XBOS) GetEnergiseMessage() *EnergiseMessage {
	if m != nil {
		return m.EnergiseMessage
	}
	return nil
}

type Resource struct {
	Transport            Transport `protobuf:"varint,1,opt,name=transport,proto3,enum=xbospb.Transport" json:"transport,omitempty"`
	Namespace            string    `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service              string    `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Instance             string    `protobuf:"bytes,4,opt,name=instance,proto3" json:"instance,omitempty"`
	Location             string    `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_xbos_dcf0799e4426b35d, []int{1}
}
func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (dst *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(dst, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetTransport() Transport {
	if m != nil {
		return m.Transport
	}
	return Transport_WAVEMQ
}

func (m *Resource) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Resource) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Resource) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *Resource) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func init() {
	proto.RegisterType((*XBOS)(nil), "xbospb.XBOS")
	proto.RegisterType((*Resource)(nil), "xbospb.Resource")
	proto.RegisterEnum("xbospb.Transport", Transport_name, Transport_value)
}

func init() { proto.RegisterFile("xbos.proto", fileDescriptor_xbos_dcf0799e4426b35d) }

var fileDescriptor_xbos_dcf0799e4426b35d = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0xdf, 0x6e, 0x12, 0x41,
	0x14, 0xc6, 0x5d, 0xad, 0xc8, 0x9e, 0x22, 0x2d, 0xd3, 0x5a, 0x47, 0x34, 0xa6, 0xf6, 0xaa, 0xf1,
	0x02, 0x13, 0x30, 0x41, 0x2f, 0xd4, 0x14, 0xe8, 0x1f, 0x8d, 0xc4, 0x3a, 0x34, 0xad, 0x77, 0xcd,
	0xb0, 0x1c, 0xea, 0xa6, 0xec, 0xcc, 0x66, 0x67, 0x68, 0xf1, 0x45, 0xfc, 0xf3, 0x0c, 0xbe, 0x88,
	0xcf, 0xa4, 0x31, 0x31, 0xbb, 0x3b, 0x03, 0xec, 0x82, 0x77, 0x7b, 0xce, 0xf7, 0xfd, 0xbe, 0x9c,
	0x49, 0x3e, 0x00, 0x98, 0xf4, 0xa5, 0xaa, 0x85, 0x91, 0xd4, 0x92, 0x14, 0xe2, 0xef, 0xb0, 0x5f,
	0x2d, 0x7f, 0xe6, 0x81, 0x3f, 0xd2, 0x52, 0xa4, 0xfb, 0xaa, 0xeb, 0x4b, 0x6d, 0x3e, 0xd7, 0x06,
	0x28, 0x74, 0x80, 0x1a, 0x23, 0xb3, 0xd8, 0x54, 0x5f, 0x94, 0xc6, 0xe0, 0x3c, 0x90, 0xc2, 0xd7,
	0xd2, 0x6e, 0x4b, 0x21, 0x8f, 0x2e, 0xa7, 0x9e, 0xf2, 0x35, 0xd7, 0x5a, 0xc8, 0x01, 0xda, 0x79,
	0x38, 0xc2, 0x89, 0xd2, 0xdc, 0x86, 0xba, 0x5e, 0xa3, 0x69, 0x25, 0x14, 0x18, 0x5d, 0xf8, 0xca,
	0x58, 0x77, 0xfe, 0x16, 0x60, 0xe5, 0x53, 0xeb, 0x43, 0x8f, 0xbc, 0x80, 0xd2, 0x91, 0xb9, 0xaa,
	0xc3, 0x35, 0xa7, 0xf5, 0x6d, 0x67, 0x77, 0xb5, 0xbe, 0x59, 0x4b, 0x4f, 0xae, 0xcd, 0x6b, 0x2c,
	0xe3, 0x24, 0x5d, 0xd8, 0xb0, 0x73, 0x8b, 0xbd, 0xf7, 0xc5, 0x65, 0x4f, 0x73, 0xad, 0x68, 0x23,
	0x09, 0x78, 0x98, 0x0f, 0x98, 0xb3, 0xb0, 0x65, 0x1c, 0x39, 0x84, 0xca, 0x6c, 0xdd, 0x45, 0xa5,
	0xf8, 0x05, 0xd2, 0xe7, 0x49, 0xd8, 0x83, 0xc5, 0x30, 0x63, 0x60, 0x8b, 0x0c, 0x79, 0x07, 0x24,
	0x7e, 0xd9, 0x5b, 0x79, 0xd2, 0xc1, 0x2b, 0xdf, 0xc3, 0x38, 0x1e, 0xe9, 0x20, 0x49, 0xaa, 0xda,
	0xa4, 0x45, 0x07, 0x5b, 0x42, 0x91, 0x53, 0xd8, 0xca, 0x6c, 0xf7, 0x3c, 0x3d, 0xe6, 0xda, 0x97,
	0x82, 0x62, 0x92, 0xf7, 0x78, 0x69, 0xde, 0xd4, 0xc5, 0xfe, 0x43, 0x93, 0xd7, 0x50, 0x36, 0x4a,
	0x5b, 0x0a, 0x8d, 0x13, 0x4d, 0x87, 0x49, 0xde, 0x56, 0x2e, 0xcf, 0xa8, 0x2c, 0xe7, 0x26, 0x6f,
	0xa0, 0xdc, 0x41, 0xa1, 0xbb, 0x71, 0x61, 0xd2, 0xf7, 0x7d, 0x75, 0xb2, 0x01, 0x59, 0x99, 0xe5,
	0xec, 0xa4, 0x09, 0xa6, 0x4a, 0xe7, 0x2a, 0xc1, 0xbf, 0xa5, 0xf8, 0x86, 0xc5, 0x8f, 0x13, 0x31,
	0x65, 0x57, 0xc3, 0xd9, 0x40, 0x5e, 0xc1, 0xb4, 0x75, 0x06, 0xfd, 0x9e, 0xa2, 0xf7, 0x2c, 0x7a,
	0x66, 0xe4, 0x14, 0xbe, 0x7b, 0x3d, 0x3f, 0xc6, 0xb8, 0x2d, 0xa9, 0xc1, 0x7f, 0xe4, 0xf0, 0x03,
	0x23, 0x1b, 0x7c, 0x38, 0x3f, 0x92, 0x23, 0xa8, 0xb4, 0xb8, 0xf2, 0xbd, 0x1e, 0x46, 0x57, 0xe9,
	0x45, 0x63, 0x45, 0x7f, 0x39, 0xd9, 0x96, 0x2c, 0x38, 0xd8, 0x22, 0x44, 0x5e, 0x42, 0xa9, 0xdd,
	0x68, 0xc6, 0x45, 0x3e, 0x88, 0x78, 0x80, 0xf4, 0xb7, 0x93, 0x2d, 0xfe, 0xbc, 0xc8, 0x32, 0x56,
	0xd2, 0x82, 0xb5, 0x7d, 0xf3, 0x6b, 0xb2, 0x3d, 0xfd, 0x93, 0xd2, 0xf7, 0x2d, 0x9d, 0xd3, 0x59,
	0x1e, 0xd8, 0xf9, 0xe9, 0x40, 0x91, 0xa1, 0x92, 0xe3, 0xc8, 0x43, 0xf2, 0x0c, 0x5c, 0x1d, 0x71,
	0xa1, 0x42, 0x19, 0x69, 0x1a, 0x27, 0x95, 0xeb, 0x15, 0x9b, 0x74, 0x62, 0x05, 0x36, 0xf3, 0x90,
	0x47, 0xe0, 0x0a, 0x1e, 0xa0, 0x0a, 0xb9, 0x87, 0xf4, 0xe6, 0xb6, 0xb3, 0xeb, 0xb2, 0xd9, 0x82,
	0x50, 0xb8, 0xa3, 0x30, 0x8a, 0x0b, 0x47, 0x6f, 0x25, 0x9a, 0x1d, 0x49, 0x15, 0x8a, 0xbe, 0x50,
	0x9a, 0x0b, 0x0f, 0xe9, 0x4a, 0x22, 0x4d, 0xe7, 0x58, 0x1b, 0x49, 0x2f, 0x2d, 0xf7, 0xed, 0x54,
	0xb3, 0xf3, 0xd3, 0x27, 0xe0, 0x4e, 0xef, 0x20, 0x00, 0x85, 0xb3, 0xbd, 0xd3, 0xfd, 0xee, 0xc7,
	0xf5, 0x1b, 0xa4, 0x08, 0x2b, 0x87, 0xec, 0xb8, 0xbd, 0xee, 0xf4, 0x0b, 0xc9, 0xff, 0x4a, 0xe3,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x66, 0x4f, 0x26, 0xf8, 0x04, 0x00, 0x00,
}
