device_info:
  veraplus_ip: 192.168.1.3

variables:
  temperature:
          device_id: 13
          service_id: TemperatureSensor1
          variable_name: CurrentTemperature
  humidity:
          device_id: 15
          service_id: HumiditySensor1
          variable_name: CurrentLevel
