database:
  host:
  port:
  username:
  password:
  database:
  ssl:
  verify_ssl:
  measurement:

xbos:
  wave:
  wavemq:
  namespace:
  entity:

data_source:
  variables:
    solar_production:
    building_load:
    battery_soc:
  agg:
  window:
  max_battery_soc:
  min_battery_soc:

data_sink:
  output_format:
  filename:
  topic_map:
    battery_setpoint:
  max_battery_rate:
  min_battery_rate: