xbos:
    waved: localhost:777
    wavemq: localhost:4516
    publish_rate: 300
    entity:
    namespace:
    service_name_map:
        thermostats:
          flexstat_test/thermostat_west/actuation/control_flag: False
          flexstat_test/thermostat_east/actuation/control_flag: True
    id: controlflag-driver